spring.application.name=web
server.port=5052
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db

spring.datasource.username=root
spring.datasource.password=Ravi@1219

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
file.upload-dir=uploads